# Generated by Django 2.2 on 2020-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Nowe'), (1, 'Rozwiązywane'), (2, 'Oczekujące'), (3, 'Rozwiązane'), (4, 'Zwrócone')], default=0),
        ),
    ]
