# Generated by Django 2.2 on 2020-08-11 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200715_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
