# Generated by Django 2.2 on 2020-06-13 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, null=True)),
                ('surname', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(null=True)),
                ('priority', models.IntegerField(choices=[(0, 'Niski'), (1, 'Normalny'), (2, 'Wysoki'), (3, 'Natychmiastowy'), (4, 'Krytyczny')], default=1)),
                ('status', models.IntegerField(choices=[(0, 'Nowe'), (1, 'Rozwiązywane'), (2, 'Oczekujące'), (3, 'Rozwiązane'), (4, 'Zwrócone')], default=1)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
