# Generated by Django 2.2 on 2020-06-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200616_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Issue'),
        ),
    ]
